### ISSUE TITLE
Okteto login fails for PRs from forked repositories

### ISSUE THREAD

**Issue by jessedobbelaere** [okteto/deploy-preview#32]
I have an open-source repository where `okteto/login` and `okteto/deploy-preview` works like a charm. Okteto login is done with:

```yaml
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
```

However, when someone makes a PR (from a fork of the repository), the github action fails with:

```
> Run okteto/login@master
...
Okteto API token is required
```

**The reason is that GitHub secrets (`OKTETO_TOKEN`) are not passed to workflows that are triggered by a pull request from a fork. Which kind of defeats the purpose of the branch preview deploy for open-source projects.** For good reasons though, since it’s important that the author of a pull request can’t access the repository’s secrets (e.g. by updating a workflow file to print out the secrets instead of running tests).

I thought about using `pull_request_target` as event to run the action against: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks However, this will do the checkout from the **PR base** (the master branch) and not include the code changes done in the PR itself. The code changes are not visible after deploy.

**I wonder if Okteto has a good suggestion/solution to get branch preview environments (from forks) working for open-source projects**. Hardcoding the okteto `token` in the github action is not a viable solution 😅 

In an open-source context, it's probably necessary to only let it deploy to a preview environment after a maintainer approves the PR or adds a label, to make sure malicious PR attempts do not auto-deploy to the K8s cluster. It's easy to solve with the `pull_request` types field or by checking for a `deploy` label before running the step: 

```yaml
if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy') }}
```

However, a contributor can still push code _after_ the label got added. And I'm still looking for a solution for GitHub to read the `OKTETO_TOKEN` secret.

**Comment by rberrelleza** [comment]
I want to keep this open to track the general story around 'open source repositories using okteto preview envs'. @jLopezbarb  what do you think about this issue?

**Comment by jessedobbelaere** [comment]
Aha thanks for that article! It helps to make the use of `pull_request_target` more clear. Adding a `deploy` label by a maintainer seems easier than writing `/ok-to-test sha=f892417` indeed. I'll do a small test.

Thanks for creating the issue to add more events to `okteto/deploy-preview` 🙌
