### ISSUE TITLE
Avoid "sh" error in entrypoint.sh line 21

### ISSUE THREAD

**Issue by pchico83** [okteto/deploy-preview#4]
<img width="1308" alt="Screenshot 2021-07-21 at 18 01 47" src="https://user-images.githubusercontent.com/7474696/126521630-ec6b593a-00d5-4ff4-a9c3-4c4d9d2c73d4.png">

**Comment by rberrelleza** [comment]
That's a syntax error in the entrypoint.sh, in the section about private certs. Can we also check if this is happening in the other actions?
