### ISSUE TITLE
Add support for debug logging / vage logging when unauthorized

### ISSUE THREAD

**Issue by rhino-acerta** [okteto/deploy-preview#52]
We ran into the following issue:

![image](https://github.com/okteto/deploy-preview/assets/116354717/3e2adb22-a855-467a-bb47-54ec036be62c)

Re-running the action (with this box checked) did not change the output logs:
![image](https://github.com/okteto/deploy-preview/assets/116354717/1d4d9851-977b-4f6e-82a3-257d2b81d77a)

We forked this repo and manually added `--log-level debug`, and the output was:
![image](https://github.com/okteto/deploy-preview/assets/116354717/f121fd47-6540-4757-86df-0cdf7b5dc47d)

However working with a fork is inconvenient. And an expiring token ... is sadly to be expected to happen again.
So we'd like improved logs - or the ability to adjust log levels.

**Comment by ifbyol** [comment]
Hi @rhino-acerta ! Thanks for the report. Right now we don't have a way to do it but we will triage with the product team the addition of a way to enable the debug logs in the action. We will also review the error returned to make it clearer.

**Comment by ifbyol** [comment]
Hi @rhino-acerta ! We have done the change and the github action supports now a way of increasing the debug level through `log-level` parameter or through GitHub Action UI with the "Enable debug logging" option
